<?php
echo       '<div class="footer" id="jobs_page_footer">
                <!-- Jira link-->
                <div class="logofooter">
                    <img src="images/image1.jpg" alt="HJDJ Logo">
                </div>
          
                <div class="objfooter">
                    <h3 class="jobs_page_heading">Contact</h3>
                    <div class="link">
                        <a href="https://hjdj2025swin.atlassian.net/jira/software/projects/SCRUM/boards/1/backlog?atlOrigin=eyJpIjoiNTNmYmIyMzMyZDlhNGJhNzllODI0YTMyNmJkMWEzNDEiLCJwIjoiaiJ9">Jira Project</a>
                    </div>
                    <div class="email">
                        <p>Email:</p>
                        <a href="mailto:someone@example.com">HJDJcarrier@hjdj.com.au</a>
                    </div>
                    <div class="megaphonetelephone">
                        <p>Tel: 408-486-1405</p>
                    </div>
                </div>
                
                <div class="objfooter">
                    <h3 class="jobs_page_heading">Company</h3>
                    <div class="link">
                        <p>About us</p>
                    </div>
                    <div class="email">
                        <p>Event</p>
                    </div>
                    <div class="megaphonetelephone">
                        <p>Terms and conditions</p>
                    </div>
                </div>

                <div class="objfooter">
                    <h3 class="jobs_page_heading">Follow Us</h3>
                <div class="link">
                    <a href="https://github.com/HJDJ-tech/COS10026-Project-Part-2" target="_blank">GitHub</a>
                </div>
                    <div class="email">
                        <p>Instagram</p>
                    </div>
                    <div class="megaphonetelephone">
                        <p>Twitter</p>
                    </div>
                </div>
            </div>';
?>